name: pull_request_build

on:
  pull_request:
    branches:
      - main

jobs:
  run_unit_tests_and_linter:
    name: Run unit tests and linters
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: set go version
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --out-format=colored-line-number
